/* 
 * Power MES Connector
 *
 * The custom connector used by Power MES by EOS Solutions.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// CompaniescompanyIdNotificationssystemIdBody
    /// </summary>
    [DataContract]
        public partial class CompaniescompanyIdNotificationssystemIdBody :  IEquatable<CompaniescompanyIdNotificationssystemIdBody>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CompaniescompanyIdNotificationssystemIdBody" /> class.
        /// </summary>
        /// <param name="read">read.</param>
        public CompaniescompanyIdNotificationssystemIdBody(bool? read = default(bool?))
        {
            this.Read = read;
        }
        
        /// <summary>
        /// read
        /// </summary>
        /// <value>read</value>
        [DataMember(Name="read", EmitDefaultValue=false)]
        public bool? Read { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CompaniescompanyIdNotificationssystemIdBody {\n");
            sb.Append("  Read: ").Append(Read).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CompaniescompanyIdNotificationssystemIdBody);
        }

        /// <summary>
        /// Returns true if CompaniescompanyIdNotificationssystemIdBody instances are equal
        /// </summary>
        /// <param name="input">Instance of CompaniescompanyIdNotificationssystemIdBody to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CompaniescompanyIdNotificationssystemIdBody input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Read == input.Read ||
                    (this.Read != null &&
                    this.Read.Equals(input.Read))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Read != null)
                    hashCode = hashCode * 59 + this.Read.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
