/* 
 * Power MES Connector
 *
 * The custom connector used by Power MES by EOS Solutions.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// InlineResponseDefault18Value
    /// </summary>
    [DataContract]
        public partial class InlineResponseDefault18Value :  IEquatable<InlineResponseDefault18Value>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InlineResponseDefault18Value" /> class.
        /// </summary>
        /// <param name="odataEtag">@odata.etag.</param>
        /// <param name="systemId">systemId.</param>
        /// <param name="jobNo">jobNo.</param>
        /// <param name="jobTaskNo">jobTaskNo.</param>
        /// <param name="jobTaskType">jobTaskType.</param>
        /// <param name="description">description.</param>
        public InlineResponseDefault18Value(string odataEtag = default(string), string systemId = default(string), string jobNo = default(string), string jobTaskNo = default(string), string jobTaskType = default(string), string description = default(string))
        {
            this.OdataEtag = odataEtag;
            this.SystemId = systemId;
            this.JobNo = jobNo;
            this.JobTaskNo = jobTaskNo;
            this.JobTaskType = jobTaskType;
            this.Description = description;
        }
        
        /// <summary>
        /// @odata.etag
        /// </summary>
        /// <value>@odata.etag</value>
        [DataMember(Name="@odata.etag", EmitDefaultValue=false)]
        public string OdataEtag { get; set; }

        /// <summary>
        /// systemId
        /// </summary>
        /// <value>systemId</value>
        [DataMember(Name="systemId", EmitDefaultValue=false)]
        public string SystemId { get; set; }

        /// <summary>
        /// jobNo
        /// </summary>
        /// <value>jobNo</value>
        [DataMember(Name="jobNo", EmitDefaultValue=false)]
        public string JobNo { get; set; }

        /// <summary>
        /// jobTaskNo
        /// </summary>
        /// <value>jobTaskNo</value>
        [DataMember(Name="jobTaskNo", EmitDefaultValue=false)]
        public string JobTaskNo { get; set; }

        /// <summary>
        /// jobTaskType
        /// </summary>
        /// <value>jobTaskType</value>
        [DataMember(Name="jobTaskType", EmitDefaultValue=false)]
        public string JobTaskType { get; set; }

        /// <summary>
        /// description
        /// </summary>
        /// <value>description</value>
        [DataMember(Name="description", EmitDefaultValue=false)]
        public string Description { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InlineResponseDefault18Value {\n");
            sb.Append("  OdataEtag: ").Append(OdataEtag).Append("\n");
            sb.Append("  SystemId: ").Append(SystemId).Append("\n");
            sb.Append("  JobNo: ").Append(JobNo).Append("\n");
            sb.Append("  JobTaskNo: ").Append(JobTaskNo).Append("\n");
            sb.Append("  JobTaskType: ").Append(JobTaskType).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as InlineResponseDefault18Value);
        }

        /// <summary>
        /// Returns true if InlineResponseDefault18Value instances are equal
        /// </summary>
        /// <param name="input">Instance of InlineResponseDefault18Value to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InlineResponseDefault18Value input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.OdataEtag == input.OdataEtag ||
                    (this.OdataEtag != null &&
                    this.OdataEtag.Equals(input.OdataEtag))
                ) && 
                (
                    this.SystemId == input.SystemId ||
                    (this.SystemId != null &&
                    this.SystemId.Equals(input.SystemId))
                ) && 
                (
                    this.JobNo == input.JobNo ||
                    (this.JobNo != null &&
                    this.JobNo.Equals(input.JobNo))
                ) && 
                (
                    this.JobTaskNo == input.JobTaskNo ||
                    (this.JobTaskNo != null &&
                    this.JobTaskNo.Equals(input.JobTaskNo))
                ) && 
                (
                    this.JobTaskType == input.JobTaskType ||
                    (this.JobTaskType != null &&
                    this.JobTaskType.Equals(input.JobTaskType))
                ) && 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.OdataEtag != null)
                    hashCode = hashCode * 59 + this.OdataEtag.GetHashCode();
                if (this.SystemId != null)
                    hashCode = hashCode * 59 + this.SystemId.GetHashCode();
                if (this.JobNo != null)
                    hashCode = hashCode * 59 + this.JobNo.GetHashCode();
                if (this.JobTaskNo != null)
                    hashCode = hashCode * 59 + this.JobTaskNo.GetHashCode();
                if (this.JobTaskType != null)
                    hashCode = hashCode * 59 + this.JobTaskType.GetHashCode();
                if (this.Description != null)
                    hashCode = hashCode * 59 + this.Description.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
