/* 
 * Power MES Connector
 *
 * The custom connector used by Power MES by EOS Solutions.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// InlineResponseDefault10Value
    /// </summary>
    [DataContract]
        public partial class InlineResponseDefault10Value :  IEquatable<InlineResponseDefault10Value>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InlineResponseDefault10Value" /> class.
        /// </summary>
        /// <param name="odataEtag">@odata.etag.</param>
        /// <param name="systemId">systemId.</param>
        /// <param name="tableNo">tableNo.</param>
        /// <param name="column1Value">column1Value.</param>
        /// <param name="column2Value">column2Value.</param>
        /// <param name="column3Value">column3Value.</param>
        /// <param name="column4Value">column4Value.</param>
        /// <param name="column5Value">column5Value.</param>
        /// <param name="column6Value">column6Value.</param>
        /// <param name="column7Value">column7Value.</param>
        /// <param name="column8Value">column8Value.</param>
        /// <param name="column9Value">column9Value.</param>
        /// <param name="column10Value">column10Value.</param>
        /// <param name="panelIdFilter">panelIdFilter.</param>
        /// <param name="tableNoFilter">tableNoFilter.</param>
        /// <param name="customFilter1">customFilter1.</param>
        /// <param name="customFilter2">customFilter2.</param>
        /// <param name="customFilter3">customFilter3.</param>
        /// <param name="customFilter4">customFilter4.</param>
        /// <param name="customFilter5">customFilter5.</param>
        /// <param name="customFilter6">customFilter6.</param>
        /// <param name="customFilter7">customFilter7.</param>
        /// <param name="customFilter8">customFilter8.</param>
        /// <param name="customFilter9">customFilter9.</param>
        /// <param name="customFilter10">customFilter10.</param>
        public InlineResponseDefault10Value(string odataEtag = default(string), string systemId = default(string), decimal? tableNo = default(decimal?), string column1Value = default(string), string column2Value = default(string), string column3Value = default(string), string column4Value = default(string), string column5Value = default(string), string column6Value = default(string), string column7Value = default(string), string column8Value = default(string), string column9Value = default(string), string column10Value = default(string), string panelIdFilter = default(string), string tableNoFilter = default(string), string customFilter1 = default(string), string customFilter2 = default(string), string customFilter3 = default(string), string customFilter4 = default(string), string customFilter5 = default(string), string customFilter6 = default(string), string customFilter7 = default(string), string customFilter8 = default(string), string customFilter9 = default(string), string customFilter10 = default(string))
        {
            this.OdataEtag = odataEtag;
            this.SystemId = systemId;
            this.TableNo = tableNo;
            this.Column1Value = column1Value;
            this.Column2Value = column2Value;
            this.Column3Value = column3Value;
            this.Column4Value = column4Value;
            this.Column5Value = column5Value;
            this.Column6Value = column6Value;
            this.Column7Value = column7Value;
            this.Column8Value = column8Value;
            this.Column9Value = column9Value;
            this.Column10Value = column10Value;
            this.PanelIdFilter = panelIdFilter;
            this.TableNoFilter = tableNoFilter;
            this.CustomFilter1 = customFilter1;
            this.CustomFilter2 = customFilter2;
            this.CustomFilter3 = customFilter3;
            this.CustomFilter4 = customFilter4;
            this.CustomFilter5 = customFilter5;
            this.CustomFilter6 = customFilter6;
            this.CustomFilter7 = customFilter7;
            this.CustomFilter8 = customFilter8;
            this.CustomFilter9 = customFilter9;
            this.CustomFilter10 = customFilter10;
        }
        
        /// <summary>
        /// @odata.etag
        /// </summary>
        /// <value>@odata.etag</value>
        [DataMember(Name="@odata.etag", EmitDefaultValue=false)]
        public string OdataEtag { get; set; }

        /// <summary>
        /// systemId
        /// </summary>
        /// <value>systemId</value>
        [DataMember(Name="systemId", EmitDefaultValue=false)]
        public string SystemId { get; set; }

        /// <summary>
        /// tableNo
        /// </summary>
        /// <value>tableNo</value>
        [DataMember(Name="tableNo", EmitDefaultValue=false)]
        public decimal? TableNo { get; set; }

        /// <summary>
        /// column1Value
        /// </summary>
        /// <value>column1Value</value>
        [DataMember(Name="column1Value", EmitDefaultValue=false)]
        public string Column1Value { get; set; }

        /// <summary>
        /// column2Value
        /// </summary>
        /// <value>column2Value</value>
        [DataMember(Name="column2Value", EmitDefaultValue=false)]
        public string Column2Value { get; set; }

        /// <summary>
        /// column3Value
        /// </summary>
        /// <value>column3Value</value>
        [DataMember(Name="column3Value", EmitDefaultValue=false)]
        public string Column3Value { get; set; }

        /// <summary>
        /// column4Value
        /// </summary>
        /// <value>column4Value</value>
        [DataMember(Name="column4Value", EmitDefaultValue=false)]
        public string Column4Value { get; set; }

        /// <summary>
        /// column5Value
        /// </summary>
        /// <value>column5Value</value>
        [DataMember(Name="column5Value", EmitDefaultValue=false)]
        public string Column5Value { get; set; }

        /// <summary>
        /// column6Value
        /// </summary>
        /// <value>column6Value</value>
        [DataMember(Name="column6Value", EmitDefaultValue=false)]
        public string Column6Value { get; set; }

        /// <summary>
        /// column7Value
        /// </summary>
        /// <value>column7Value</value>
        [DataMember(Name="column7Value", EmitDefaultValue=false)]
        public string Column7Value { get; set; }

        /// <summary>
        /// column8Value
        /// </summary>
        /// <value>column8Value</value>
        [DataMember(Name="column8Value", EmitDefaultValue=false)]
        public string Column8Value { get; set; }

        /// <summary>
        /// column9Value
        /// </summary>
        /// <value>column9Value</value>
        [DataMember(Name="column9Value", EmitDefaultValue=false)]
        public string Column9Value { get; set; }

        /// <summary>
        /// column10Value
        /// </summary>
        /// <value>column10Value</value>
        [DataMember(Name="column10Value", EmitDefaultValue=false)]
        public string Column10Value { get; set; }

        /// <summary>
        /// panelIdFilter
        /// </summary>
        /// <value>panelIdFilter</value>
        [DataMember(Name="panelIdFilter", EmitDefaultValue=false)]
        public string PanelIdFilter { get; set; }

        /// <summary>
        /// tableNoFilter
        /// </summary>
        /// <value>tableNoFilter</value>
        [DataMember(Name="tableNoFilter", EmitDefaultValue=false)]
        public string TableNoFilter { get; set; }

        /// <summary>
        /// customFilter1
        /// </summary>
        /// <value>customFilter1</value>
        [DataMember(Name="customFilter1", EmitDefaultValue=false)]
        public string CustomFilter1 { get; set; }

        /// <summary>
        /// customFilter2
        /// </summary>
        /// <value>customFilter2</value>
        [DataMember(Name="customFilter2", EmitDefaultValue=false)]
        public string CustomFilter2 { get; set; }

        /// <summary>
        /// customFilter3
        /// </summary>
        /// <value>customFilter3</value>
        [DataMember(Name="customFilter3", EmitDefaultValue=false)]
        public string CustomFilter3 { get; set; }

        /// <summary>
        /// customFilter4
        /// </summary>
        /// <value>customFilter4</value>
        [DataMember(Name="customFilter4", EmitDefaultValue=false)]
        public string CustomFilter4 { get; set; }

        /// <summary>
        /// customFilter5
        /// </summary>
        /// <value>customFilter5</value>
        [DataMember(Name="customFilter5", EmitDefaultValue=false)]
        public string CustomFilter5 { get; set; }

        /// <summary>
        /// customFilter6
        /// </summary>
        /// <value>customFilter6</value>
        [DataMember(Name="customFilter6", EmitDefaultValue=false)]
        public string CustomFilter6 { get; set; }

        /// <summary>
        /// customFilter7
        /// </summary>
        /// <value>customFilter7</value>
        [DataMember(Name="customFilter7", EmitDefaultValue=false)]
        public string CustomFilter7 { get; set; }

        /// <summary>
        /// customFilter8
        /// </summary>
        /// <value>customFilter8</value>
        [DataMember(Name="customFilter8", EmitDefaultValue=false)]
        public string CustomFilter8 { get; set; }

        /// <summary>
        /// customFilter9
        /// </summary>
        /// <value>customFilter9</value>
        [DataMember(Name="customFilter9", EmitDefaultValue=false)]
        public string CustomFilter9 { get; set; }

        /// <summary>
        /// customFilter10
        /// </summary>
        /// <value>customFilter10</value>
        [DataMember(Name="customFilter10", EmitDefaultValue=false)]
        public string CustomFilter10 { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InlineResponseDefault10Value {\n");
            sb.Append("  OdataEtag: ").Append(OdataEtag).Append("\n");
            sb.Append("  SystemId: ").Append(SystemId).Append("\n");
            sb.Append("  TableNo: ").Append(TableNo).Append("\n");
            sb.Append("  Column1Value: ").Append(Column1Value).Append("\n");
            sb.Append("  Column2Value: ").Append(Column2Value).Append("\n");
            sb.Append("  Column3Value: ").Append(Column3Value).Append("\n");
            sb.Append("  Column4Value: ").Append(Column4Value).Append("\n");
            sb.Append("  Column5Value: ").Append(Column5Value).Append("\n");
            sb.Append("  Column6Value: ").Append(Column6Value).Append("\n");
            sb.Append("  Column7Value: ").Append(Column7Value).Append("\n");
            sb.Append("  Column8Value: ").Append(Column8Value).Append("\n");
            sb.Append("  Column9Value: ").Append(Column9Value).Append("\n");
            sb.Append("  Column10Value: ").Append(Column10Value).Append("\n");
            sb.Append("  PanelIdFilter: ").Append(PanelIdFilter).Append("\n");
            sb.Append("  TableNoFilter: ").Append(TableNoFilter).Append("\n");
            sb.Append("  CustomFilter1: ").Append(CustomFilter1).Append("\n");
            sb.Append("  CustomFilter2: ").Append(CustomFilter2).Append("\n");
            sb.Append("  CustomFilter3: ").Append(CustomFilter3).Append("\n");
            sb.Append("  CustomFilter4: ").Append(CustomFilter4).Append("\n");
            sb.Append("  CustomFilter5: ").Append(CustomFilter5).Append("\n");
            sb.Append("  CustomFilter6: ").Append(CustomFilter6).Append("\n");
            sb.Append("  CustomFilter7: ").Append(CustomFilter7).Append("\n");
            sb.Append("  CustomFilter8: ").Append(CustomFilter8).Append("\n");
            sb.Append("  CustomFilter9: ").Append(CustomFilter9).Append("\n");
            sb.Append("  CustomFilter10: ").Append(CustomFilter10).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as InlineResponseDefault10Value);
        }

        /// <summary>
        /// Returns true if InlineResponseDefault10Value instances are equal
        /// </summary>
        /// <param name="input">Instance of InlineResponseDefault10Value to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InlineResponseDefault10Value input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.OdataEtag == input.OdataEtag ||
                    (this.OdataEtag != null &&
                    this.OdataEtag.Equals(input.OdataEtag))
                ) && 
                (
                    this.SystemId == input.SystemId ||
                    (this.SystemId != null &&
                    this.SystemId.Equals(input.SystemId))
                ) && 
                (
                    this.TableNo == input.TableNo ||
                    (this.TableNo != null &&
                    this.TableNo.Equals(input.TableNo))
                ) && 
                (
                    this.Column1Value == input.Column1Value ||
                    (this.Column1Value != null &&
                    this.Column1Value.Equals(input.Column1Value))
                ) && 
                (
                    this.Column2Value == input.Column2Value ||
                    (this.Column2Value != null &&
                    this.Column2Value.Equals(input.Column2Value))
                ) && 
                (
                    this.Column3Value == input.Column3Value ||
                    (this.Column3Value != null &&
                    this.Column3Value.Equals(input.Column3Value))
                ) && 
                (
                    this.Column4Value == input.Column4Value ||
                    (this.Column4Value != null &&
                    this.Column4Value.Equals(input.Column4Value))
                ) && 
                (
                    this.Column5Value == input.Column5Value ||
                    (this.Column5Value != null &&
                    this.Column5Value.Equals(input.Column5Value))
                ) && 
                (
                    this.Column6Value == input.Column6Value ||
                    (this.Column6Value != null &&
                    this.Column6Value.Equals(input.Column6Value))
                ) && 
                (
                    this.Column7Value == input.Column7Value ||
                    (this.Column7Value != null &&
                    this.Column7Value.Equals(input.Column7Value))
                ) && 
                (
                    this.Column8Value == input.Column8Value ||
                    (this.Column8Value != null &&
                    this.Column8Value.Equals(input.Column8Value))
                ) && 
                (
                    this.Column9Value == input.Column9Value ||
                    (this.Column9Value != null &&
                    this.Column9Value.Equals(input.Column9Value))
                ) && 
                (
                    this.Column10Value == input.Column10Value ||
                    (this.Column10Value != null &&
                    this.Column10Value.Equals(input.Column10Value))
                ) && 
                (
                    this.PanelIdFilter == input.PanelIdFilter ||
                    (this.PanelIdFilter != null &&
                    this.PanelIdFilter.Equals(input.PanelIdFilter))
                ) && 
                (
                    this.TableNoFilter == input.TableNoFilter ||
                    (this.TableNoFilter != null &&
                    this.TableNoFilter.Equals(input.TableNoFilter))
                ) && 
                (
                    this.CustomFilter1 == input.CustomFilter1 ||
                    (this.CustomFilter1 != null &&
                    this.CustomFilter1.Equals(input.CustomFilter1))
                ) && 
                (
                    this.CustomFilter2 == input.CustomFilter2 ||
                    (this.CustomFilter2 != null &&
                    this.CustomFilter2.Equals(input.CustomFilter2))
                ) && 
                (
                    this.CustomFilter3 == input.CustomFilter3 ||
                    (this.CustomFilter3 != null &&
                    this.CustomFilter3.Equals(input.CustomFilter3))
                ) && 
                (
                    this.CustomFilter4 == input.CustomFilter4 ||
                    (this.CustomFilter4 != null &&
                    this.CustomFilter4.Equals(input.CustomFilter4))
                ) && 
                (
                    this.CustomFilter5 == input.CustomFilter5 ||
                    (this.CustomFilter5 != null &&
                    this.CustomFilter5.Equals(input.CustomFilter5))
                ) && 
                (
                    this.CustomFilter6 == input.CustomFilter6 ||
                    (this.CustomFilter6 != null &&
                    this.CustomFilter6.Equals(input.CustomFilter6))
                ) && 
                (
                    this.CustomFilter7 == input.CustomFilter7 ||
                    (this.CustomFilter7 != null &&
                    this.CustomFilter7.Equals(input.CustomFilter7))
                ) && 
                (
                    this.CustomFilter8 == input.CustomFilter8 ||
                    (this.CustomFilter8 != null &&
                    this.CustomFilter8.Equals(input.CustomFilter8))
                ) && 
                (
                    this.CustomFilter9 == input.CustomFilter9 ||
                    (this.CustomFilter9 != null &&
                    this.CustomFilter9.Equals(input.CustomFilter9))
                ) && 
                (
                    this.CustomFilter10 == input.CustomFilter10 ||
                    (this.CustomFilter10 != null &&
                    this.CustomFilter10.Equals(input.CustomFilter10))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.OdataEtag != null)
                    hashCode = hashCode * 59 + this.OdataEtag.GetHashCode();
                if (this.SystemId != null)
                    hashCode = hashCode * 59 + this.SystemId.GetHashCode();
                if (this.TableNo != null)
                    hashCode = hashCode * 59 + this.TableNo.GetHashCode();
                if (this.Column1Value != null)
                    hashCode = hashCode * 59 + this.Column1Value.GetHashCode();
                if (this.Column2Value != null)
                    hashCode = hashCode * 59 + this.Column2Value.GetHashCode();
                if (this.Column3Value != null)
                    hashCode = hashCode * 59 + this.Column3Value.GetHashCode();
                if (this.Column4Value != null)
                    hashCode = hashCode * 59 + this.Column4Value.GetHashCode();
                if (this.Column5Value != null)
                    hashCode = hashCode * 59 + this.Column5Value.GetHashCode();
                if (this.Column6Value != null)
                    hashCode = hashCode * 59 + this.Column6Value.GetHashCode();
                if (this.Column7Value != null)
                    hashCode = hashCode * 59 + this.Column7Value.GetHashCode();
                if (this.Column8Value != null)
                    hashCode = hashCode * 59 + this.Column8Value.GetHashCode();
                if (this.Column9Value != null)
                    hashCode = hashCode * 59 + this.Column9Value.GetHashCode();
                if (this.Column10Value != null)
                    hashCode = hashCode * 59 + this.Column10Value.GetHashCode();
                if (this.PanelIdFilter != null)
                    hashCode = hashCode * 59 + this.PanelIdFilter.GetHashCode();
                if (this.TableNoFilter != null)
                    hashCode = hashCode * 59 + this.TableNoFilter.GetHashCode();
                if (this.CustomFilter1 != null)
                    hashCode = hashCode * 59 + this.CustomFilter1.GetHashCode();
                if (this.CustomFilter2 != null)
                    hashCode = hashCode * 59 + this.CustomFilter2.GetHashCode();
                if (this.CustomFilter3 != null)
                    hashCode = hashCode * 59 + this.CustomFilter3.GetHashCode();
                if (this.CustomFilter4 != null)
                    hashCode = hashCode * 59 + this.CustomFilter4.GetHashCode();
                if (this.CustomFilter5 != null)
                    hashCode = hashCode * 59 + this.CustomFilter5.GetHashCode();
                if (this.CustomFilter6 != null)
                    hashCode = hashCode * 59 + this.CustomFilter6.GetHashCode();
                if (this.CustomFilter7 != null)
                    hashCode = hashCode * 59 + this.CustomFilter7.GetHashCode();
                if (this.CustomFilter8 != null)
                    hashCode = hashCode * 59 + this.CustomFilter8.GetHashCode();
                if (this.CustomFilter9 != null)
                    hashCode = hashCode * 59 + this.CustomFilter9.GetHashCode();
                if (this.CustomFilter10 != null)
                    hashCode = hashCode * 59 + this.CustomFilter10.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
