/* 
 * Power PLM Connector
 *
 * The custom connector used by Power PLM by EOS Solutions.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// InlineResponseDefault3Value
    /// </summary>
    [DataContract]
        public partial class InlineResponseDefault3Value :  IEquatable<InlineResponseDefault3Value>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InlineResponseDefault3Value" /> class.
        /// </summary>
        /// <param name="odataEtag">@odata.etag.</param>
        /// <param name="systemId">systemId.</param>
        /// <param name="languageCode">languageCode.</param>
        /// <param name="captionName">captionName.</param>
        /// <param name="captionValue">captionValue.</param>
        public InlineResponseDefault3Value(string odataEtag = default(string), string systemId = default(string), string languageCode = default(string), string captionName = default(string), string captionValue = default(string))
        {
            this.OdataEtag = odataEtag;
            this.SystemId = systemId;
            this.LanguageCode = languageCode;
            this.CaptionName = captionName;
            this.CaptionValue = captionValue;
        }
        
        /// <summary>
        /// @odata.etag
        /// </summary>
        /// <value>@odata.etag</value>
        [DataMember(Name="@odata.etag", EmitDefaultValue=false)]
        public string OdataEtag { get; set; }

        /// <summary>
        /// systemId
        /// </summary>
        /// <value>systemId</value>
        [DataMember(Name="systemId", EmitDefaultValue=false)]
        public string SystemId { get; set; }

        /// <summary>
        /// languageCode
        /// </summary>
        /// <value>languageCode</value>
        [DataMember(Name="languageCode", EmitDefaultValue=false)]
        public string LanguageCode { get; set; }

        /// <summary>
        /// captionName
        /// </summary>
        /// <value>captionName</value>
        [DataMember(Name="captionName", EmitDefaultValue=false)]
        public string CaptionName { get; set; }

        /// <summary>
        /// captionValue
        /// </summary>
        /// <value>captionValue</value>
        [DataMember(Name="captionValue", EmitDefaultValue=false)]
        public string CaptionValue { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InlineResponseDefault3Value {\n");
            sb.Append("  OdataEtag: ").Append(OdataEtag).Append("\n");
            sb.Append("  SystemId: ").Append(SystemId).Append("\n");
            sb.Append("  LanguageCode: ").Append(LanguageCode).Append("\n");
            sb.Append("  CaptionName: ").Append(CaptionName).Append("\n");
            sb.Append("  CaptionValue: ").Append(CaptionValue).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as InlineResponseDefault3Value);
        }

        /// <summary>
        /// Returns true if InlineResponseDefault3Value instances are equal
        /// </summary>
        /// <param name="input">Instance of InlineResponseDefault3Value to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InlineResponseDefault3Value input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.OdataEtag == input.OdataEtag ||
                    (this.OdataEtag != null &&
                    this.OdataEtag.Equals(input.OdataEtag))
                ) && 
                (
                    this.SystemId == input.SystemId ||
                    (this.SystemId != null &&
                    this.SystemId.Equals(input.SystemId))
                ) && 
                (
                    this.LanguageCode == input.LanguageCode ||
                    (this.LanguageCode != null &&
                    this.LanguageCode.Equals(input.LanguageCode))
                ) && 
                (
                    this.CaptionName == input.CaptionName ||
                    (this.CaptionName != null &&
                    this.CaptionName.Equals(input.CaptionName))
                ) && 
                (
                    this.CaptionValue == input.CaptionValue ||
                    (this.CaptionValue != null &&
                    this.CaptionValue.Equals(input.CaptionValue))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.OdataEtag != null)
                    hashCode = hashCode * 59 + this.OdataEtag.GetHashCode();
                if (this.SystemId != null)
                    hashCode = hashCode * 59 + this.SystemId.GetHashCode();
                if (this.LanguageCode != null)
                    hashCode = hashCode * 59 + this.LanguageCode.GetHashCode();
                if (this.CaptionName != null)
                    hashCode = hashCode * 59 + this.CaptionName.GetHashCode();
                if (this.CaptionValue != null)
                    hashCode = hashCode * 59 + this.CaptionValue.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
