/* 
 * Power PLM Connector
 *
 * The custom connector used by Power PLM by EOS Solutions.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// InlineResponseDefault25Value
    /// </summary>
    [DataContract]
        public partial class InlineResponseDefault25Value :  IEquatable<InlineResponseDefault25Value>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InlineResponseDefault25Value" /> class.
        /// </summary>
        /// <param name="odataEtag">@odata.etag.</param>
        /// <param name="systemId">systemId.</param>
        /// <param name="faultAreaCode">faultAreaCode.</param>
        /// <param name="faultSubAreaCode">faultSubAreaCode.</param>
        /// <param name="symptomCode">symptomCode.</param>
        /// <param name="code">code.</param>
        /// <param name="description">description.</param>
        public InlineResponseDefault25Value(string odataEtag = default(string), string systemId = default(string), string faultAreaCode = default(string), string faultSubAreaCode = default(string), string symptomCode = default(string), string code = default(string), string description = default(string))
        {
            this.OdataEtag = odataEtag;
            this.SystemId = systemId;
            this.FaultAreaCode = faultAreaCode;
            this.FaultSubAreaCode = faultSubAreaCode;
            this.SymptomCode = symptomCode;
            this.Code = code;
            this.Description = description;
        }
        
        /// <summary>
        /// @odata.etag
        /// </summary>
        /// <value>@odata.etag</value>
        [DataMember(Name="@odata.etag", EmitDefaultValue=false)]
        public string OdataEtag { get; set; }

        /// <summary>
        /// systemId
        /// </summary>
        /// <value>systemId</value>
        [DataMember(Name="systemId", EmitDefaultValue=false)]
        public string SystemId { get; set; }

        /// <summary>
        /// faultAreaCode
        /// </summary>
        /// <value>faultAreaCode</value>
        [DataMember(Name="faultAreaCode", EmitDefaultValue=false)]
        public string FaultAreaCode { get; set; }

        /// <summary>
        /// faultSubAreaCode
        /// </summary>
        /// <value>faultSubAreaCode</value>
        [DataMember(Name="faultSubAreaCode", EmitDefaultValue=false)]
        public string FaultSubAreaCode { get; set; }

        /// <summary>
        /// symptomCode
        /// </summary>
        /// <value>symptomCode</value>
        [DataMember(Name="symptomCode", EmitDefaultValue=false)]
        public string SymptomCode { get; set; }

        /// <summary>
        /// code
        /// </summary>
        /// <value>code</value>
        [DataMember(Name="code", EmitDefaultValue=false)]
        public string Code { get; set; }

        /// <summary>
        /// description
        /// </summary>
        /// <value>description</value>
        [DataMember(Name="description", EmitDefaultValue=false)]
        public string Description { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InlineResponseDefault25Value {\n");
            sb.Append("  OdataEtag: ").Append(OdataEtag).Append("\n");
            sb.Append("  SystemId: ").Append(SystemId).Append("\n");
            sb.Append("  FaultAreaCode: ").Append(FaultAreaCode).Append("\n");
            sb.Append("  FaultSubAreaCode: ").Append(FaultSubAreaCode).Append("\n");
            sb.Append("  SymptomCode: ").Append(SymptomCode).Append("\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as InlineResponseDefault25Value);
        }

        /// <summary>
        /// Returns true if InlineResponseDefault25Value instances are equal
        /// </summary>
        /// <param name="input">Instance of InlineResponseDefault25Value to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InlineResponseDefault25Value input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.OdataEtag == input.OdataEtag ||
                    (this.OdataEtag != null &&
                    this.OdataEtag.Equals(input.OdataEtag))
                ) && 
                (
                    this.SystemId == input.SystemId ||
                    (this.SystemId != null &&
                    this.SystemId.Equals(input.SystemId))
                ) && 
                (
                    this.FaultAreaCode == input.FaultAreaCode ||
                    (this.FaultAreaCode != null &&
                    this.FaultAreaCode.Equals(input.FaultAreaCode))
                ) && 
                (
                    this.FaultSubAreaCode == input.FaultSubAreaCode ||
                    (this.FaultSubAreaCode != null &&
                    this.FaultSubAreaCode.Equals(input.FaultSubAreaCode))
                ) && 
                (
                    this.SymptomCode == input.SymptomCode ||
                    (this.SymptomCode != null &&
                    this.SymptomCode.Equals(input.SymptomCode))
                ) && 
                (
                    this.Code == input.Code ||
                    (this.Code != null &&
                    this.Code.Equals(input.Code))
                ) && 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.OdataEtag != null)
                    hashCode = hashCode * 59 + this.OdataEtag.GetHashCode();
                if (this.SystemId != null)
                    hashCode = hashCode * 59 + this.SystemId.GetHashCode();
                if (this.FaultAreaCode != null)
                    hashCode = hashCode * 59 + this.FaultAreaCode.GetHashCode();
                if (this.FaultSubAreaCode != null)
                    hashCode = hashCode * 59 + this.FaultSubAreaCode.GetHashCode();
                if (this.SymptomCode != null)
                    hashCode = hashCode * 59 + this.SymptomCode.GetHashCode();
                if (this.Code != null)
                    hashCode = hashCode * 59 + this.Code.GetHashCode();
                if (this.Description != null)
                    hashCode = hashCode * 59 + this.Description.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
